dist: xenial

language: cpp

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T print_ip-1.0.$TRAVIS_BUILD_NUMBER.deb -uansochnev:$BINTRAY_API_KEY "https://api.bintray.com/content/ansochnev/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/pool/main/h4/print_ip-1.0.$TRAVIS_BUILD_NUMBER.deb;deb_distribution=homework;deb_component=main;deb_architecture=amd64;publish=1"
